/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLessonplanSessionStartRouteImport } from './routes/api/lessonplan/session-start'
import { Route as ApiLessonplanSaveRouteImport } from './routes/api/lessonplan/save'
import { Route as ApiLessonplanInterRouteImport } from './routes/api/lessonplan/inter'
import { Route as ApiLessonplanChatRouteImport } from './routes/api/lessonplan/chat'
import { Route as ApiAdminSplatRouteImport } from './routes/api/admin/$'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonplanSessionStartRoute =
  ApiLessonplanSessionStartRouteImport.update({
    id: '/api/lessonplan/session-start',
    path: '/api/lessonplan/session-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLessonplanSaveRoute = ApiLessonplanSaveRouteImport.update({
  id: '/api/lessonplan/save',
  path: '/api/lessonplan/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonplanInterRoute = ApiLessonplanInterRouteImport.update({
  id: '/api/lessonplan/inter',
  path: '/api/lessonplan/inter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonplanChatRoute = ApiLessonplanChatRouteImport.update({
  id: '/api/lessonplan/chat',
  path: '/api/lessonplan/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSplatRoute = ApiAdminSplatRouteImport.update({
  id: '/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/lessonplan/chat': typeof ApiLessonplanChatRoute
  '/api/lessonplan/inter': typeof ApiLessonplanInterRoute
  '/api/lessonplan/save': typeof ApiLessonplanSaveRoute
  '/api/lessonplan/session-start': typeof ApiLessonplanSessionStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/lessonplan/chat': typeof ApiLessonplanChatRoute
  '/api/lessonplan/inter': typeof ApiLessonplanInterRoute
  '/api/lessonplan/save': typeof ApiLessonplanSaveRoute
  '/api/lessonplan/session-start': typeof ApiLessonplanSessionStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/lessonplan/chat': typeof ApiLessonplanChatRoute
  '/api/lessonplan/inter': typeof ApiLessonplanInterRoute
  '/api/lessonplan/save': typeof ApiLessonplanSaveRoute
  '/api/lessonplan/session-start': typeof ApiLessonplanSessionStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/admin/$'
    | '/api/lessonplan/chat'
    | '/api/lessonplan/inter'
    | '/api/lessonplan/save'
    | '/api/lessonplan/session-start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/admin/$'
    | '/api/lessonplan/chat'
    | '/api/lessonplan/inter'
    | '/api/lessonplan/save'
    | '/api/lessonplan/session-start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/api/admin/$'
    | '/api/lessonplan/chat'
    | '/api/lessonplan/inter'
    | '/api/lessonplan/save'
    | '/api/lessonplan/session-start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ApiAdminSplatRoute: typeof ApiAdminSplatRoute
  ApiLessonplanChatRoute: typeof ApiLessonplanChatRoute
  ApiLessonplanInterRoute: typeof ApiLessonplanInterRoute
  ApiLessonplanSaveRoute: typeof ApiLessonplanSaveRoute
  ApiLessonplanSessionStartRoute: typeof ApiLessonplanSessionStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lessonplan/session-start': {
      id: '/api/lessonplan/session-start'
      path: '/api/lessonplan/session-start'
      fullPath: '/api/lessonplan/session-start'
      preLoaderRoute: typeof ApiLessonplanSessionStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lessonplan/save': {
      id: '/api/lessonplan/save'
      path: '/api/lessonplan/save'
      fullPath: '/api/lessonplan/save'
      preLoaderRoute: typeof ApiLessonplanSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lessonplan/inter': {
      id: '/api/lessonplan/inter'
      path: '/api/lessonplan/inter'
      fullPath: '/api/lessonplan/inter'
      preLoaderRoute: typeof ApiLessonplanInterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lessonplan/chat': {
      id: '/api/lessonplan/chat'
      path: '/api/lessonplan/chat'
      fullPath: '/api/lessonplan/chat'
      preLoaderRoute: typeof ApiLessonplanChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/$': {
      id: '/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ApiAdminSplatRoute: ApiAdminSplatRoute,
  ApiLessonplanChatRoute: ApiLessonplanChatRoute,
  ApiLessonplanInterRoute: ApiLessonplanInterRoute,
  ApiLessonplanSaveRoute: ApiLessonplanSaveRoute,
  ApiLessonplanSessionStartRoute: ApiLessonplanSessionStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
